[package]
name = "web"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
log = "0.4"
wasm-logger = "0.2"
yew = { version = "0.20", features = ["csr"] }
yew-router = "0.17"
