[package]
name = "bulletforcehax2_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
photon_lib = { path = "../photon_lib" }
anyhow = "1"
bytes = "1"
futures-util = "0.3"
hyper = { version = "0.14", features = ["full"] } # TODO: be more specific
hyper-tls = "0.5"
regex = "1.6"
serde_json = "1"
tokio = { version = "1", features = ["full"] } # TODO: be more specific
tokio-tungstenite = { version = "0.17", features = ["native-tls"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.3", features = ["full"] }
tracing = "0.1"
futures = "0.3.24"
