workspace.members = [
    "photon_lib",
    "bulletforcehax2_lib",
    "bulletforcehax2_server",
    "bulletforcehax2_web",
]

[profile.release-publish]
inherits = "release"
lto = true
codegen-units = 1
