workspace.members = [
    "photon_lib",
    "bulletforcehax2_lib",
    "bulletforcehax2_ui",
    "bulletforcehax2_app",
    "tao_egui",
]

[profile.release-publish]
inherits = "release"
lto = true
codegen-units = 1
