name: "Test Suite"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: sudo apt update
      - run: sudo apt install -y libwebkit2gtk-4.0-dev libgtk-3-dev
      # Ensure build does not fail due to missing directory.
      # We don't need front-end to be built for our tests but
      # build will fail if this directory is not present.
      - run: mkdir dist
      - run: sudo apt install -y libwebkit2gtk-4.1-dev libgtk-3-dev libjavascriptcoregtk-4.1-dev libsoup-3.0-dev
      - run: cargo test --all-features
